### ISSUE TITLE
Re-enable web process

### ISSUE THREAD

**Issue by joshmoore** [openmicroscopy/devspace#12]
Currently web is not started in the slave (see OMERO-start job). This would be a first step towards enabling the robot job.

 * [ ] Add SERVICE_NAME in docker-compose.yml for external access (this could either be done on the `nginx` or the `slave` container)
 * [ ] Re-enable `web start` in the job with the appropriate configuration
 
Note: *a later refactoring may move the SERVICE_NAME of `jenkins` in favor of having `nginx` be the main point of entry*

cc: @aleksandra-tarkowska

**Comment by joshmoore** [comment]
This issue was created by migrating some checklist items from https://trello.com/c/z5LrlWMy/20-spaces-work

**Comment by aleksandra-tarkowska** [comment]
http://10.0.49.1:52888/job/OMERO-web/34/consoleFull this is running omero web from Omero.py

**Comment by aleksandra-tarkowska** [comment]
https://github.com/joshmoore/devspace/pull/1

**Comment by joshmoore** [comment]
Closing in favor of https://github.com/openmicroscopy/devspace/pull/19
