### ISSUE TITLE
Add evaluation exe4j for Windows clients

### ISSUE THREAD

**Issue by sbesson** [openmicroscopy/devspace#15]
As reported by @gusferguson, currently we have no `exe4j` installed on the Jenkins slave meaning no Windows Insight/Importer artifacts are created by the OMERO-build job.

Minimally, we might want to download https://www.ej-technologies.com/download/exe4j/files and include it in the `slave/Dockerfile` in the right place.

**Comment by manics** [comment]
In case it helps: https://github.com/openmicroscopy/infrastructure/blob/master/ansible/roles/omero-build/tasks/main.yml#L102

**Comment by pwalczysko** [comment]
I am a bit worried about the ROI folder work not being tested in Windows insight for a long time. Specific graphical problems in Insight on Windows are a known issue (Importer for one example).
