### ISSUE TITLE
Minor environment variable cleanups

### ISSUE THREAD

**Issue by joshmoore** [openmicroscopy/devspace#24]
* JENKINS_LABEL is likely no longer needed:
   * [ ] https://github.com/openmicroscopy/devspace/pull/20/files#diff-4e5e90c6228fd48698d074241c2ba760R37
   * [ ] https://github.com/openmicroscopy/devspace/pull/20/files#diff-4e5e90c6228fd48698d074241c2ba760R52
   * [ ] https://github.com/openmicroscopy/devspace/pull/20/files#diff-4e5e90c6228fd48698d074241c2ba760R64
   * [ ] https://github.com/openmicroscopy/devspace/pull/20/files#diff-4e5e90c6228fd48698d074241c2ba760R102
 * Similar for JENKINS_MODE

**Comment by aleksandra-tarkowska** [comment]
this is cleaned up in https://github.com/aleksandra-tarkowska/devspace/blob/round2/docker-compose.yml

**Comment by joshmoore** [comment]
:+1:
