### ISSUE TITLE
Enable compose restart persistence

### ISSUE THREAD

**Issue by joshmoore** [openmicroscopy/devspace#26]
All containers should use external storage (especially PG) so that on restarting (even deleting & recreating) the containers, the pre-stop state returns.

**Comment by aleksandra-tarkowska** [comment]
Done https://github.com/openmicroscopy/devspace/pull/31

**Comment by aleksandra-tarkowska** [comment]
we need to preserver data repo dir as well

**Comment by joshmoore** [comment]
:+1:
