### ISSUE TITLE
full-repo job

### ISSUE THREAD

**Issue by joshmoore** [openmicroscopy/devspace#27]
## Current state

Up to devspace `0.6.0`, the Bio-Formats branch of devspace is limited to the following CI pipeline:

- a push job merges all PRs opened against a development branch
- an Ant job builds and runs the unit tests using the Ant  build system
- a Maven job builds and runs and the unit tests using the Maven build system (allowing the coupling to the OMERO builds)

## Limitations

The main limitation of this pipeline compared to the reference jobs in https://ci.openmicroscopy.org/view/Bio-Formats is the absence of CI jobs running the automated tests against the data repository. 

Adding support for these jobs is becoming increasingly critical as:

- the mainline CI jobs are been increasingly suffering from instabilities (loss of network, OOMs) which are affecting its build times as well as its reliability

<img width="1383" alt="screen shot 2017-12-16 at 09 58 30" src="https://user-images.githubusercontent.com/1355463/34069009-c4fd01d8-e247-11e7-8c5d-f7f15024d255.png">

- Bio-Formats development is effectively happening for multiple targets: next patch release, next minor release, epics... Currently we lack the infrastructure to isolate a body of work e.g. into a dedicated integration branch which is fully tested against the data repository. Opening a PR against develop and getting it tested in ci-master is effectively the only solution to get a PR fully tested.

## Proposal

The following section describe a series of changes implemented in the `next-ci` devspace at various levels (Bio-Formats, Jenkins, configuration, data repository) to address the limitations described above.

### Docker infrastructure

A top-level `Dockerfile` image has been introduced the Bio-Formats source code repository for the integration branch (currently limited to `ant jars tools`) - see https://github.com/openmicroscopy/bioformats/pull/3013

### CI changes

The Bio-Formats CI queue has been modified in the `next-ci` devspace to run the following:

- the `BIOFORMATS-image` job builds a Docker image on a `docker` node from the integration branch created by `BIOFORMATS-push`
- a new `BIOFORMATS-test-repo` pipeline job has been introduced with performs the following steps:
   1.  lists all top-level folders under the read-only copy of the curated data repository on GPFS
   2. triggers an array of `BIOFORMATS-test-repo` jobs with the format folder name as a parameter
   3.  each `BIOFORMATS-test-folder` job runs the automated tests in `test-suite` by running the docker and mounting the path to the format data and configuration folders i.e.

   ```
  $ docker run -v /path/to/data/curated/<format>:/opt/data -v /path/to/configuration/curated/<format>:/opt/config <container_name>
  ```
<img width="1383" alt="screen shot 2017-12-16 at 07 34 35" src="https://user-images.githubusercontent.com/1355463/34067968-9d6826ac-e233-11e7-9a4f-104fbab5abce.png">

### Data repository changes

The proposal above modifies the default expectation in terms of testing since every `curated/<format>` folder needs to be testable in complete isolation.

A few changes were necessary at the data repository layout to:
- all unsupported formats have been moved under a top-level `curated/unsupported` folder (see [private config PR](https://github.com/openmicroscopy/data_repo_config/pull/249))
- all existing symlinks cross format folders have been reviewed and removed (see [private config PR](https://github.com/openmicroscopy/data_repo_config/pull/251))
- as the Docker image is `openjdk` based, all the JDK-dependent pixels tests need to be reviewed ([private config PR](https://github.com/openmicroscopy/data_repo_config/pull/250))

### Source code changes

Additional changes were required at the configuration or testing level:
- some readers require adjustements to account for different file listing order in the Docker container - see https://github.com/openmicroscopy/bioformats/pull/3022
- the robustness of memo tests in a parallelized context has been improved - https://github.com/openmicroscopy/bioformats/pull/3026

## Still to be decided

- [ ] Dockerfile API esp. the decision on hardcoding the `test-automated` entrypoint vs creating a wrapper script with different runtime targets (e.g. `tools` to run the command line tools, `test` for the automated tests)
- [ ] BIOFORMATS-ant job could be fully deprecated in favor of 2 jobs: BIOFORMATS-image for building step and a downstream BIOFORMATS-test job running the unit tests separately since these are memory intensive and time-consuming
- [ ] alternate/better namings for new CI jobs

## Integration

Once the above are resolved and this has been agreed, the next steps should be to

- port the changes made to the devspace repository on `next-ci` as a PR against this repository
- schedule the timeline/roadmap for the release of the next development of `devspace`:  `0.7.0`? beginning of 2018?

NB: issue description edited by @sbesson

**Comment by manics** [comment]
> the BIOFORMATS-image job builds a Docker image on a docker node from the integration branch created by BIOFORMATS-push

- Will this require devspace to have access to the host docker daemon?
- IIUC the long term plan is to get devspace working on a distributed system (e.g. for Kubernetes building Docker images is possible but adds more complexity- it'll require extra permissions, and you'll need to push to a registry, since by nature it's distributed).

**Comment by joshmoore** [comment]
> Will this require devspace to have access to the host docker daemon?

Yes, or it does currently.

> you'll need to push to a registry, since by nature it's distributed

I tested pushing to bintray: https://bintray.com/scc/docker/openmicroscopy:bioformats but ended up removing it since it wasn't yet needed. Having either a cluster-wide repository or one specifically for the devspace would be :+1:

**Comment by sbesson** [comment]
@manics that is right, one of the major infrastructure changes at the `docker-compose` level  is the addition of a `docker` node which bind mounts to the Docker socket. 

From the timeline perspective, the main question is: assuming we define long-term as 6-12 months, should we account for this immediately or get it working under the current paradigm, start consuming it in the next 3-6 months and then review this strategy to address the concerns you mention when the new infrastructure is in place?
