### ISSUE TITLE
Build:  Failed to connect to updates.jenkins-ci.org

### ISSUE THREAD

**Issue by aleksandra-tarkowska** [openmicroscopy/devspace#40]
We need workaround for 

```
Step 5 : RUN /usr/local/bin/plugins.sh /usr/share/jenkins/ref/plugins.txt
 ---> Running in f80dec721f77
Downloading swarm:2.0
Downloading git:2.4.0
curl: (7) Failed to connect to updates.jenkins-ci.org port 443: Connection timed out
ERROR: Service 'jenkins' failed to build: The command '/bin/sh -c /usr/local/bin/plugins.sh /usr/share/jenkins/ref/plugins.txt' returned a non-zero code: 7
```

**Comment by joshmoore** [comment]
Perhaps add `--retry` to the curl call? http://stackoverflow.com/a/13554435

**Comment by aleksandra-tarkowska** [comment]
We'd need to maintain then https://github.com/jenkinsci/docker/blob/master/plugins.sh

**Comment by aleksandra-tarkowska** [comment]
Happened once so far

**Comment by joshmoore** [comment]
Currently trying with something like this:

```
omero@jamoore-docker:/data/metadata52$ git diff jenkins/
diff --git a/jenkins/Dockerfile b/jenkins/Dockerfile
index 9c7af26..ea2d50c 100644
--- a/jenkins/Dockerfile
+++ b/jenkins/Dockerfile
@@ -5,4 +5,5 @@ MAINTAINER OME
 ENV JAVA_OPTS "-Dhudson.model.DirectoryBrowserSupport.CSP="

 COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
-RUN /usr/local/bin/plugins.sh /usr/share/jenkins/ref/plugins.txt
+RUN echo "/usr/bin/curl --retry 5" >> /tmp/curl
```

but perhaps we are being throttled.

**Comment by aleksandra-tarkowska** [comment]
if mirror was dead for an entire day, will this change anything?

**Comment by joshmoore** [comment]
Perhaps related to http://www.b.shuttle.de/hayek/hayek/jochen/wp/blog-en/2012/09/18/curl-hangs-talking-to-a-web-site-through-https-actually-a-tsl-version-issue/

**Comment by joshmoore** [comment]
Or https://github.com/docker/docker/issues/2011#issuecomment-78296360

**Comment by joshmoore** [comment]
Or maybe http://stackoverflow.com/a/25130606

```
* Hostname was NOT found in DNS cache
```

Any thoughts, @manics ?

**Comment by joshmoore** [comment]
General issue looks like this with more debugging:

```
 ---> Running in b4b3cd5d828f
Downloading swarm:2.0
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 52.91.151.148...
* Connected to updates.jenkins-ci.org (52.91.151.148) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]

```

**Comment by joshmoore** [comment]
I've worked around for the mount by creating a "prefetch" script which can be used outside of docker.

**Comment by manics** [comment]
Alternative DNS servers seem to work:

```
$ docker run -it --rm centos
[root@924ac27ae487 /]# yum install -y -q bind-utils
...
[root@924ac27ae487 /]# dig www.docker.com @8.8.4.4
...
www.docker.com.         104     IN      A       104.239.220.248
```

**Comment by joshmoore** [comment]
I'm currently using the last commit from https://github.com/joshmoore/devspace/tree/round2 (https://github.com/joshmoore/devspace/commit/b2ba3ebb1dd659d94b5a0605b14c9f643e55223b) if that helps you, @aleksandra-tarkowska, though @manics did point out that we need to make sure all our docker daemons are using `--mtu 1400`.

**Comment by joshmoore** [comment]
See https://github.com/openmicroscopy/infrastructure/pull/67

**Comment by joshmoore** [comment]
I'm going to assume that 67 (mtu setting) will help in most cases. If that doesn't work, we can look into the prefetching strategy which is roughly equivalent to running our own update site. The next solution (which I looked into briefly) would be to use a caching proxy like squid.
