### ISSUE TITLE
Add ssl self signed cert for web

### ISSUE THREAD

**Issue by aleksandra-tarkowska** [openmicroscopy/devspace#42]

**Comment by manics** [comment]
If it helps there's an ansible role: https://github.com/openmicroscopy/infrastructure/tree/master/ansible/roles/nginx-ssl-selfsigned

**Comment by aleksandra-tarkowska** [comment]
Thanks, waiting for #31 to continue on this topic

**Comment by aleksandra-tarkowska** [comment]
done in https://github.com/openmicroscopy/devspace/pull/31
