### ISSUE TITLE
Slave container encoding issue

### ISSUE THREAD

**Issue by sbesson** [openmicroscopy/devspace#61]
While testing the redeployment of the devspace, I realized that the slave Docker container has locale issues

```
[sbesson@ome-c6220-1-4 slave]$ docker build -t slave .
Sending build context to Docker daemon 7.168 kB
Step 1 : FROM openmicroscopy/devslave-c7:0.2.1
...
Step 35 : CMD /tmp/run.sh
 ---> Running in e8db8a36e88d
 ---> 68a842d39b72
Removing intermediate container e8db8a36e88d
Successfully built 68a842d39b72
docker run -it slave bash
[sbesson@ome-c6220-1-4 slave]$ docker run -it slave bash
[omero@9c14e5352b81 linux]$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

This leads to errors especially when running unit tests. Briefly looked at the build logs and issues seem to originate after the reinstallation of `glibc-common`

```
+ yum -y install zlib-devel libjpeg-devel gcc
...
+ yum -y install gcc-c++
Failed to set locale, defaulting to C
```

I'll work on a minimal container to reproduce

**Comment by sbesson** [comment]
```
FROM openmicroscopy/devslave-c7:0.2.1

MAINTAINER OME

RUN yum -y update
```

is sufficient to reproduce the issue

**Comment by aleksandra-tarkowska** [comment]
http://blog.earth-works.com/2014/02/10/fixing-lc-locale-issues-in-centos-and-rhel/ will this help?

**Comment by sbesson** [comment]
There is no such file unfortunately. Pinning down the issue to `glibc-common` as indicated by various SO/Google threads, the following Dockerfile is sufficient to reproduce the issue:

```
FROM openmicroscopy/devslave-c7:0.2.1
MAINTAINER OME

RUN yum -y update glibc-common
```

I'll look into excluding `glibc-common` from the upgrades and see if this helps.

**Comment by sbesson** [comment]
Update: https://github.com/openmicroscopy/devspace/pull/59/commits/3e6ec1b27838ed453175fab3dc94dc300c788f2d seems to resolve the encoding issue as all the tests (Bio-Formats + OMERO) are now passing from the `HEAD` of develop. More investigation might be required to investigate if and how this can be backported to the base image.
