### ISSUE TITLE
Bump swarm-client plugin

### ISSUE THREAD

**Issue by sbesson** [openmicroscopy/devspace#86]
See https://jenkins.io/security/advisory/2017-10-11/#swarm-plugin-client-bundled-vulnerable-version-of-the-commons-httpclient-library

The version of the [Swarm plugin](https://wiki.jenkins.io/display/JENKINS/Swarm+Plugin) will need to be upgraded to 3.5 or above (currently 3.6). The client plugin should be upgraded in coordination which probably requires bumping https://github.com/openmicroscopy/devslave-c7-docker/blob/master/Dockerfile#L28 (or rebuilding the image with a different argument if possible).

**Comment by joshmoore** [comment]
https://github.com/openmicroscopy/devspace/pull/91 upgrades the swarm plugin, but likely we should just remove it. We are no longer using it in favor of nodes which autoconnect over a docker network.

**Comment by sbesson** [comment]
Closing as addressed by 0.7.0, we can capture the proposed cleanup in a separate issue.
